name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or your version

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Example: Deploy using rsync to a remote server
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2ZEhSPcoy+a8OJDMDhItJQuCaBN8mCrijaAtAoskMNn07d6zvliXzYBQuJszbjPfF8X5TgCfEPlMDWdyLbddnyuqffF8mXHhTjDNEuVWeBameP+kv6UDuq7EZznb8WxxUsuJnESPa95lpV4/2gF5Zqh+m5CIxG/GE9uS51HVqVEG6XfahdEMucuQlnqKjjzVfSPOtPlmPWFWhq/y0yNioKRggB2vVIWTX0NCbIEBcuiO740x0u0xYozzuxikrGSRL5q6rotKhOx5CxxY/fYxzsGLjENr5xDEFZnCgtIxuh9zicDiy7iA7hzj0jNRVY3SSJ6OU0XIl/HpnQ+wvaKyeMhTKMP5tnQFG3lBjY6PefM4JgqhCSk3BoLvLbluz+aX37I+ZcrL8+gGoSydRhVyFcjwz3TXDPCkKs/KHNQftIyvwVVlQ096k7cxZokwkbvHy2+iwHj3DwEirdUncyyeA0wIVu9nOj/Vs4plv/9kEglMtNVmN9Jj353+zvN3X/k7cmpIzTHqhPxevq9lz94RTye8zIBG7VZ7i5ZxQUbkT57r8X2hoyh35fhz/rhwRJMtdlXhqzmcJN14GLsb8Pc9N+y0bSkKP2nvpAPLBC4eKt5obBz50cEePjwm+zsXh8pXcXIGuQUxuQc47gZXqAbLQIcfnktJiTV6J6F5FLYItww== github-actions-deploy"
          remote-user: your-user
          server-ip: 13.60.240.76
          remote-path: /var/www/your-app
          local-path: build
