

name: Build and Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (Install Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Adjust this to match your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures that the deploy job runs after the build job

    steps:
      # Step 1: Checkout the repository again (just to be safe)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH (use the private key stored in secrets)
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAtmRIUj3KMvmvDiQzA4SLSULgmgTfJgq4o2gLQKLJDDZ9O3es75Yl
82AULibM24z3xfF+U4AnxD5TA1nci23XZ8rqn3xfJlx4U4wzRLlVngWpnj/pL+lA7quxGc
52/FscVLLiZxEj2veZaVeP9oBeWaofpuQiMRvxhPbkudR1alRBul32oXRDLnLkJZ6io481
X0jzrT5Zj1hVoav8tMjYqCkYIAdr1SFk19DQmyBAXLoju+NMdLtMWKM87sYpKxkkS+auq6
LSoTseQscWP32Mc7Bi4xDa+cQxBWZwoLSMbofc4nA4su4gO4c49IzUVWN0kiejlNFyJfx6
Z0PsL2isnjIUyjD+bZ0BRt5QY2Oj3nzOCYKoQkpNwaC7y25bs/ml9+yPmXKy/PoBqEsnUY
VchXI8M901wzwpCrPyhzUH7SMr8FVZUNPepO3MWaJMJG7x8tvosB49w8BIq3VJ3MsngNMC
FbvZzo/1bOKZb//ZBIJTLTVZjfSY9+d/s7zd1/5O3JqSM0x6oT8Xr6vZc/eEU8nvMyARu1
We4uWcUFG5E+e6/F9oaMod+X4c/64cESTLXZV4as5nCTdeBi7G/D3PTfstG0pCj9p76QDy
wQuHireaGwc+dHBHj48Jvs7F4fKV3FyBrkFMbkHOO4GV6gGy0CHH55LSYk1eieheRS2CLc
MAAAdQCwx1zwsMdc8AAAAHc3NoLXJzYQAAAgEAtmRIUj3KMvmvDiQzA4SLSULgmgTfJgq4
o2gLQKLJDDZ9O3es75Yl82AULibM24z3xfF+U4AnxD5TA1nci23XZ8rqn3xfJlx4U4wzRL
lVngWpnj/pL+lA7quxGc52/FscVLLiZxEj2veZaVeP9oBeWaofpuQiMRvxhPbkudR1alRB
ul32oXRDLnLkJZ6io481X0jzrT5Zj1hVoav8tMjYqCkYIAdr1SFk19DQmyBAXLoju+NMdL
tMWKM87sYpKxkkS+auq6LSoTseQscWP32Mc7Bi4xDa+cQxBWZwoLSMbofc4nA4su4gO4c4
9IzUVWN0kiejlNFyJfx6Z0PsL2isnjIUyjD+bZ0BRt5QY2Oj3nzOCYKoQkpNwaC7y25bs/
ml9+yPmXKy/PoBqEsnUYVchXI8M901wzwpCrPyhzUH7SMr8FVZUNPepO3MWaJMJG7x8tvo
sB49w8BIq3VJ3MsngNMCFbvZzo/1bOKZb//ZBIJTLTVZjfSY9+d/s7zd1/5O3JqSM0x6oT
8Xr6vZc/eEU8nvMyARu1We4uWcUFG5E+e6/F9oaMod+X4c/64cESTLXZV4as5nCTdeBi7G
/D3PTfstG0pCj9p76QDywQuHireaGwc+dHBHj48Jvs7F4fKV3FyBrkFMbkHOO4GV6gGy0C
HH55LSYk1eieheRS2CLcMAAAADAQABAAACAADvYq+JQZAhV5Rq+xf5hf1KKnyfqcU4KNot
nmEmdIFrhhjX9DsGOguVYoUaDdLSVjLdmhgzgACxkRtjSo4scf5GPA21RYec0cEb5udjS9
0TilsVWMy2FW8j0jSfqlyA2xRUFnUQ0W499rtjh4lr/w/Wn3LrmIFH82ULHwEU5cU1yWB7
Oth5EB8c166ZsZvFEDD83sL0nuDtQwMhLpp+rR2vmEARyau+EBZLK8af07Sl/6jm8W1nyG
xr6dQPkAZ4iocZF6wpmYraEr2k56hLrHyrWtZvL7A4IUg1zj4ErvOiHq/Kg3/nWKL1foVC
c5Q8fkyBh4UrzboEIVyGLJ/RmZDz19RerwTsNeJck7LrS+uoXTNEGeE3AUA1qadYt2LMkU
3jWDl2rCAqFMrpgeR0G+xDratglK17evU39WshEQPEw48rDzFelruoVeMayuClGmj/GYTB
ardQ1CBBoQOMQa9aFn9Oz9EAuWNCA87mcr2FwQ/MMb8HGjSW1AM/IT18TiBTXErgUiVbrt
1GyBk6WyfX5QGC8d2qp085/DJjx4na75baCiD0IiczkeMlmKEmTpMDTLpxs7dfnXzBhf1C
dELAm2txmLen50ApI9NbFQgjhSDDiFuv9HgNgGit16GeUBbVXAgIjcnl42r/QP+TRXDIDp
aYxgcZ9RxLHRbABvSBAAABAEQXwy2ga/j3sET3KTKBZXbc0FPacyQjGn0/xSX9mGtYnEOO
iy2mGewKxpvNRNlP5m4kc02zimHig8cb8Kk1PNlrUPw8WRywpgGl8Pkpdiolog2dr4oNBo
z+N7t8QtI5iAQP6yhjn30N0m4n0zTie/vKL9D1y6wuh+ixz86QyfqL4niBGidA7ejZsB2W
Uep8E8a76IiZdh9hz1Po26bOGjV1cZCFcrSV3/mLUxadsUSR7iE8FMlWNFAryTzz+QU9dK
6XCQuXk5AFJy0AhjsB4aZDhJKK6sbVu3pL3aTaaIN5aCtjn1QPYrzRIeIlBGiVD5eVJ9V2
I1NItfPuMxl7BGoAAAEBAMfbklKUtBrsEWgNWiKghZDi+GG1UkmMJuT9XU4tyOt6Va5ttZ
b/Ife0h/a8fxcsfXrN6hS10FVVM9ayP9Nb54BiengGWC8oda/FehAwYaECfBvmrVwIrnLT
zJkkfmhIAykMqsVJR+iFK6iunCpY5/otQo06vvMagWpb6eVme4uhK1PAGa3NN9hd03pqZS
QsSmGElT+0CHwH8y9CAjinVJ5EQ+dUmEu9F6X8VEy3L7e0+TMLJaMolBGRJDPoIJ/Wo3ZC
LvlUukUgaS4o3syUGgxmvNPLi+hw1HlYcyrr1gcEmIS5b0rTpqyR6bNvCeYmAVtJG9f6/1
btlqwshQQ8tM0AAAEBAOmgrM+j7eeQM5Y3Osf+DIOlQOYr1vKv6sycIy1V6AsLSV4L8OOi
dMGSdvVT/p6ppr8ZrKPi8sgEEZgxvFhrYsHGdurDaAxAqdtTfYd0kg6nxNZ4+m1Gz43hwh
ghbKgHaIDuQljBbdx5aUzqIVpYg8Yt4I6QKcmygeRM39QMOb8qKgxx63AvLhpds1Ho9JMN
N9iIBYh1nR7w7rnW+MhcsTYT1bRIZBp80UsbjUw7K2Ebe1Zu/TjWBOUk+x1ZsJzQILcSgO
ALWzSqsEmn+3WDRZTm9hQeK1b1M3z1uq/ORFf7Du36/oRSVxEvdFdMVsJlJgPtiSsgn+0j
C3H/kZi77M8AAAAVZ2l0aHViLWFjdGlvbnMtZGVwbG95AQIDBAUG
-----END OPENSSH PRIVATE KEY-----

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          # SSH into EC2 instance and run deployment commands
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.240.76 <<EOF
            # Navigate to the app directory on the EC2 instance
            cd /home/ubuntu/hello-node  # Change to your app's directory

            # Pull the latest changes from the GitHub repository
            git pull origin main

            # Install/update the dependencies
            npm install

            # Stop the app if it's already running
            pm2 stop app.js || true  # Stop the app if it's running

            # Start the app using PM2
            pm2 start app.js --name "my-node-app"  # Adjust the filename if necessary

            # Save the PM2 process list so the app can auto-start on reboot
            pm2 save

            # Optionally, you can also configure PM2 to start on system startup:
            # pm2 startup

          EOF
